### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by The-Code-Monkey** [Starklord17/threejs-t-shirt#3]
Hi, I have a client at work who need something similar to this with the ability to be able to move the uploaded image around with the front of the TShirt plus be able to download a print file e.g. just the designs how they were laid out on the tshirt, would you have any idea of how to do this.

**Comment by Starklord17** [comment]
Hi!
To add the ability to move the uploaded image around on the T-shirt and download a print file, you can use the existing Decal component's position prop to make the logo movable. Update it based on user input (e.g., drag events).
For downloading the print file, I think that you can create a separate canvas to render just the design elements without the 3D T-shirt model. You can use the same texture and position data from your 3D scene to draw on this 2D canvas.
